### ISSUE TITLE
In desktop-capture I cannot see particular windows (as in the gif), only fullscreen recording...

### ISSUE THREAD

**Issue by sapioit** [hokein/electron-sample-apps#15] opened 2015-12-27 11:43 UTC
Also, the `Disable Capture` button does not works...
Tested with `electron-v0.36.2-win32-x64` and `electron-v0.36.2-win32-ia32`.

First, saved files, than app screenshots.

![screenshot 1](https://cloud.githubusercontent.com/assets/3173159/12010087/a1d08d4a-ac9f-11e5-9e10-4597bc60baa8.png)
![screenshot 2](https://cloud.githubusercontent.com/assets/3173159/12010088/a1ec87c0-ac9f-11e5-812f-6f8a545a5f1b.png)

----

![screenshot 1](https://cloud.githubusercontent.com/assets/3173159/12010065/a83224c4-ac9e-11e5-8a1b-b33d9ade2a36.png)
![screenshot 2](https://cloud.githubusercontent.com/assets/3173159/12010066/a8332a90-ac9e-11e5-9753-838b8524439a.png)

**Comment by hokein** [comment] 2015-12-27 14:15
Could you open the dev-tools console and see the output message?

**Comment by sapioit** [comment] 2015-12-27 18:33
![screenshot 3](https://cloud.githubusercontent.com/assets/3173159/12011520/23ca49ce-acd9-11e5-8469-2747596da884.png)

**Comment by sapioit** [comment] 2015-12-27 18:41
app.js:52 for an even_numbered press, app.js:70 for an odd_numbered button press...
![screenshot 1](https://cloud.githubusercontent.com/assets/3173159/12011539/3f76dd94-acda-11e5-8a8a-c54e5f73d8eb.png)

**Comment by Raj123456788** [comment] 2016-02-12 00:24
Did you find the answer for this issue?

**Comment by sapioit** [comment] 2016-02-12 11:15
I haven't checked it ever since. Will try, one of those days... probably...

**Comment by JeffZ2013** [comment] 2016-02-24 06:39
Hi, anyone got chance check this? 
The disable capture button doesn't work for me as well, from dev-tools, localStream.stop is not a function.
electron version v0.36.5

**Comment by JeffZ2013** [comment] 2016-02-24 07:05
Found the cause and committed a fix.
MediumStream.stop deprecated.

      localStream.stop();
      localStream.getTracks()[0].stop();

**Comment by styfle** [comment] 2016-04-13 19:20
I think I fixed this in Pull Request #27

**Comment by hokein** [comment] 2016-04-13 19:50
Closing it as fixed in #27.

**Closed by hokein** 2016-04-13 19:50 UTC
